### ISSUE TITLE
Not showing in HACS

### ISSUE THREAD

**Issue by holdestmade** [jampez77/DVLA-Vehicle-Enquiry-Service#1]
Not showing in HACS

EDIT, I see the PR hasn't been approved yet, I'll manually install

https://github.com/hacs/default/pull/2058

**Comment by jampez77** [comment]
I will close this issue now. Thanks

**Comment by holdestmade** [comment]
How come ? it's not resolved, still not visible in HACS ?

**Comment by jampez77** [comment]
Because it's resolution is outside of my control.

**Comment by holdestmade** [comment]
Probably want to note that in the install instructions that its not available in HACS yet

**Comment by jampez77** [comment]
Good idea, done that now. Thanks
