### ISSUE TITLE
each Entity contains all the attributes returned by the API call?

### ISSUE THREAD

**Issue by godfreym29** [jampez77/DVLA-Vehicle-Enquiry-Service#11]
Why does each entity created by the integration contain all the data returned by the API call?
it looks like the Jason is being parsed into each entity

for instance:
the entity Colour: shows the State of "Black"
but the attibutes of it are:
> registrationNumber: *******
> taxStatus: Taxed
> taxDueDate: 2025-01-01
> motStatus: Not valid
> make: NISSAN
> yearOfManufacture: 2010
> engineCapacity: 1461
> co2Emissions: 139
> fuelType: DIESEL
> markedForExport: false
> colour: BLACK
> typeApproval: M1
> dateOfLastV5CIssued: 2021-02-11
> motExpiryDate: 2024-01-11
> wheelplan: 2 AXLE RIGID BODY
> monthOfFirstRegistration: 2010-01
> icon: mdi:spray
> friendly_name: Colour

It's the same for all the entities

**Comment by jampez77** [comment]
This sort of functionality is pretty common among other integrations so i probably won't be looking to change this.
