### ISSUE TITLE
DVLA API Key expiring due to infrequent polling

### ISSUE THREAD

**Issue by stephensalex** [jampez77/DVLA-Vehicle-Enquiry-Service#14]
The integration does not seem to poll the DVLA API frequently enough to prevent the DVLA expiring the API key. I am currently having to email the DVLA to reactivate the API key periodically. I can't see a service to call in order to force polling of the API.

**Comment by JamieNandhraPezone** [comment]
It's set to poll once a day of I recall so there might be something else going on. Not sure what though.

**Comment by stephensalex** [comment]
Thanks for the quick response, I'll double check the logs.

**Comment by jampez77** [comment]
This should be fixed in [2024.7.0](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/releases/tag/2024.7.0)
