### ISSUE TITLE
custom integration 'dvla' calls async_forward_entry_setup for integration

### ISSUE THREAD

**Issue by derekoharrow** [jampez77/DVLA-Vehicle-Enquiry-Service#15]
HA 2024.7 is reporting the following on startup:

`2024-07-16 09:50:16.417 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dvla' calls async_forward_entry_setup for integration, dvla with title: XXXXXX and entry_id: 132259d905a8d554019283897f0d6ccb, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/dvla/__init__.py, line 26: hass.async_create_task(, please create a bug report at https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/issues`

**Comment by jampez77** [comment]
Thanks for bringing this to my attention! I'll try and find some time for this one soon.

**Comment by jampez77** [comment]
This should be fixed in [2024.7.0](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/releases/tag/2024.7.0)
