### ISSUE TITLE
Add Reg to calendar entry

### ISSUE THREAD

**Issue by DJ-Q** [jampez77/DVLA-Vehicle-Enquiry-Service#17]

**Comment by jampez77** [comment]
Good suggestion, I'll have a look at this soon. Thanks 😊

**Comment by snigehere** [comment]
Thanks for your work on this integration
Would be great to have this as well .. I have two cars I am monitoring and it would be great to know which is which

**Comment by jampez77** [comment]
This should now be working in [2024.9.1](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/releases/tag/2024.9.1)

**Comment by snigehere** [comment]
many thanks
