### ISSUE TITLE
scan_interval & instance query

### ISSUE THREAD

**Issue by kylegordon** [jampez77/DVLA-Vehicle-Enquiry-Service#21]
Hi,

More of a question than an issue... 

With API rate limiting in mind, does an 'instance' and/or scan_interval apply per vehicle or per HA install?

I have about 5 vehicles I'd like to monitor (family, friends, etc), but as you can imagine that significantly alters the rate limit value I need to provide!

Looking forward to using the integration. Will certainly make scheduling MOTs a lot easier!

**Comment by jampez77** [comment]
Hey thanks for asking, it's a good question. The limit would be per car as it can only query one car at a time, bulk querying would be lovely if they did it.

Hope this helps and hope this integration makes your life a bit easier.

FYI I was looking at Halfords Autocentre Booking API recently and I think I might be able to automate the booking process with an integration. Not sure yet but confident. I know you didn't ask about it but I'm excited and need someone to tell 🙂

**Comment by kylegordon** [comment]
Awesome, thank you for the info! Halfords API sounds awesome too, definitely sounds like something helpful. You could even ask Halfords for a wee sponsorship deal :-D
