### ISSUE TITLE
Allow user to set estimated usage

### ISSUE THREAD

**Issue by jampez77** [jampez77/DVLA-Vehicle-Enquiry-Service#4]
The VESA form asks for "Estimated monthly enquiry volumes".

This is currently hard coded based on how often the integration queries the API. 

I think a good enhancement would be to allow the user to set this during config flow.

**Comment by ryanm101** [comment]
i think it's set to 10min `SCAN_INTERVAL = timedelta(minutes=10)`

Tbh this data could do hourly or even twice a day by default, as none of that data is going to change frequently.

**Comment by leeandy1** [comment]
It queries twice per day

**Comment by xhemp** [comment]
I have added this some days ago and I had to reload the integration to update the values but it's showing 20 hours ago so it's certainly not happening twice a day?

**Comment by jampez77** [comment]
This should be fixed in [2024.7.0](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/releases/tag/2024.7.0)
