### ISSUE TITLE
adding multiple vehicles no unique sensors

### ISSUE THREAD

**Issue by si458** [jampez77/DVLA-Vehicle-Enquiry-Service#5]
Hi
Brilliant integration, just one nit pick,
When u add multiple vehicles, the sensors aren't really being unique
For example the mot due date is `sensor.mot_expiry_date` and `sensor.mot_expiry_date_2` 
Where as the dvla calender entry is `calendar.dvla_reg123` and `calendar.dvla_reg1234` 
Can the sensor ids be changed to include the reg in front of the name?

**Comment by jampez77** [comment]
Firstly, thanks for using the integration and thanks for taking the time to give a suggestion. I like that idea and have added it to the to do list.

**Comment by madmic1314** [comment]
Brilliant integration - I second this change as well - we have 3 vehicles and it's difficult to keep track.

Some ideas on the sensor name could be sensor.reg.xxx or sensor.manufacturer.xxx ? The second might be difficult if people have two of the same model vehicles.

**Comment by spiderlane** [comment]
Yes this would be very useful. I really like the individual sensors (previously I used template sensors to split out the attributes) but ideally they need to be prefixed with the registration for use with more than one car.

**Comment by rudgej** [comment]
Hello. I did ask a separate question but no reply and I figured replying to this might ask a wider audience. 

There are no setup instructions and nowhere to put the api key in the HACS integration. 

Can anyone tell me where the key goes and how to call this service please ? 

Thanks

**Comment by si458** [comment]
@rudgej Once u added it in hacs, just install, it, restart ha, then fo into integrations then add the dvla, and put ur key/reg in there

**Comment by rudgej** [comment]
Thank you.

Working.

I will look in the morning but I assume I can call any registration from an automation tied to ANPR and get back the details of that vehicle not just the one added to the integration?

Many thanks
Jeremy
Sent from my iPhone

On 5 Jan 2024, at 07:46, Simon Smith ***@***.***> wrote:

﻿

@rudgej<https://github.com/rudgej> Once u added it in hacs, just install, it, restart ha, then fo into integrations then add the dvla, and put ur key/reg in there

**Comment by si458** [comment]
@rudgej NO the integration isnt designed for that!
its designed to add say your own car(s) into HA to check dates of MOT, etc, and it creates devices with entities of them
you cant call a function/automation/service to check a RANDOM car, 
(you would have to somehow add the integration every time you saw a reg, wait for it to setup/reply from entities then remove the integration! seems very hard work)

**Comment by rudgej** [comment]
Ok thanks. I will see what I can do to call the api directly. 

What I want to do it run all cars that come up on my Anpr feed and put them into a Google docs spreadsheet . Will see how I get on.

**Comment by si458** [comment]
> Ok thanks. I will see what I can do to call the api directly.
> 
> What I want to do it run all cars that come up on my Anpr feed and put them into a Google docs spreadsheet . Will see how I get on.

Yeh that won't work, unless u maybe modified the integration to add a service, which u can then input the reg and call, which then passes that reg to dvla and returns data

**Comment by rich-kettlewell** [comment]
+1 on improving the sensor names.

my 2 cars have now created sensors called "sensor.colour" and "sensor_colour_2" .. far too generic :-)

**Comment by si458** [comment]
fixed i think all, works perfectly on my setup, 2 missing lines
will use
`binary_sensor.dvla_REGHERELOWERCASE_DESCRIPTION`
`sensor.dvla_REGHERELOWERCASE_DESCRIPTION`
`calendar.dvla_REGHERELOWERCASE`

**Comment by si458** [comment]
fixed i think all, works perfectly on my setup, 2 missing lines
will use
```
binary_sensor.dvla_REGHERELOWERCASE_DESCRIPTION
sensor.dvla_REGHERELOWERCASE_DESCRIPTION
calendar.dvla_REGHERELOWERCASE
```
![image](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/assets/765314/479e5c2a-5ba9-4fa7-ba79-3c4e75ce4c94)
